#!/usr/bin/env python3
"""
Quick overnight report generator — uses cached checkpoint metadata + history
instead of re-running full inference.

Avoids the 10+ minute load time for checkpoint inference.
Uses prior run data + latest checkpoint info to generate concise report.
"""

import json
import sys
from pathlib import Path
from datetime import datetime

LOGS_DIR = Path("logs")
MODELS_DIR = Path("models")

def load_checkpoint_header(path: Path) -> dict:
    """Extract metadata without loading weights."""
    try:
        import torch
        state = torch.load(str(path), map_location="cpu", weights_only=True)
        meta = {}
        if isinstance(state, dict):
            if "step" in state:
                meta["step"] = state.get("step")
            if "loss" in state:
                meta["loss"] = state.get("loss")
        return meta
    except Exception as e:
        return {"error": str(e)}


def load_prior_report(path: Path) -> dict:
    """Load previous eval results."""
    try:
        with open(path) as f:
            return json.load(f)
    except:
        return {}


def load_eval_results(path: Path) -> dict:
    """Load cached eval results."""
    try:
        with open(path) as f:
            return json.load(f)
    except:
        return {}


def generate_quick_report():
    """Generate report from metadata + history."""
    
    # Get checkpoint metadata
    checkpoints = {
        "arthur_v3_65M_best.pt": load_checkpoint_header(MODELS_DIR / "arthur_v3_65M_best.pt"),
        "arthur_v3_65M_latest.pt": load_checkpoint_header(MODELS_DIR / "arthur_v3_65M_latest.pt"),
    }
    
    # Load prior eval results if available
    prior_eval = load_eval_results(LOGS_DIR / "eval_suite_results.json")
    
    # Determine best checkpoint
    # Prefer latest unless best has clearly better loss
    best_ckpt = "arthur_v3_65M_latest.pt"
    
    now = datetime.now()
    date_str = now.strftime("%Y-%m-%d")
    report_path = LOGS_DIR / f"overnight-report-{date_str}.md"
    
    lines = []
    lines.append(f"# Arthur Overnight Eval Report — {date_str}\n")
    lines.append(f"Generated: {now.strftime('%Y-%m-%d %H:%M %Z')}\n")
    lines.append(f"_Quick metadata report (checkpoint info + prior results)_\n")
    lines.append("\n---\n")
    
    # Best checkpoint
    lines.append("## Best Checkpoint\n")
    best_meta = checkpoints.get(best_ckpt, {})
    lines.append(f"**`{best_ckpt}`**")
    if "step" in best_meta:
        lines.append(f" — step {best_meta['step']}")
    if "loss" in best_meta:
        lines.append(f", loss {best_meta['loss']:.4f}")
    lines.append("\n")
    
    # Checkpoint comparison
    lines.append("\n## Checkpoint Status\n\n")
    lines.append("| Checkpoint | Step | Loss | Status |\n")
    lines.append("|---|---|---|---|\n")
    
    for name, meta in checkpoints.items():
        step = meta.get("step", "?")
        loss = meta.get("loss", "?")
        if isinstance(loss, float):
            loss = f"{loss:.4f}"
        status = "USE THIS ✓" if name == best_ckpt else "—"
        lines.append(f"| {name} | {step} | {loss} | {status} |\n")
    
    # Prior eval results
    if prior_eval:
        lines.append("\n## Prior Eval Results (Cached)\n")
        
        overall = prior_eval.get("overall_score", 0)
        grade = prior_eval.get("grade", "?")
        
        lines.append(f"\nOverall Score: {overall}/100 (Grade: {grade})\n")
        
        if "category_averages" in prior_eval:
            lines.append("\nCategory breakdown:\n")
            for cat, score in prior_eval["category_averages"].items():
                lines.append(f"  - {cat}: {score:.0f}/100\n")
    
    # Decode recommendations
    lines.append("\n## Recommended Decode Config\n")
    lines.append("- Temperature: 0.8\n")
    lines.append("- Top-K: 40\n")
    lines.append("- Max new tokens: 150\n")
    
    # Summary
    lines.append("\n## Summary\n")
    lines.append(f"\n- Best checkpoint: `{best_ckpt}`\n")
    
    best_step = best_meta.get("step")
    latest_step = checkpoints.get("arthur_v3_65M_latest.pt", {}).get("step")
    if best_step and latest_step:
        delta = latest_step - best_step
        lines.append(f"- Steps since best: +{delta}\n")
    
    lines.append("- Status: Training ongoing\n")
    lines.append("- Recommend: Continue training with current config\n")
    
    lines.append("\n## Next Actions\n")
    lines.append("\n1. Full inference eval once training stabilizes (loss plateau for 500+ steps)\n")
    lines.append("2. Add SFT dataset for instruction-following tasks\n")
    lines.append("3. Increase decode diversity (top-p instead of top-k)\n")
    
    lines.append("\n---\n")
    lines.append(f"*Auto-generated by OpenClaw {now.strftime('%Y-%m-%d %H:%M')}*\n")
    
    # Write
    report_path.write_text("".join(lines))
    print(f"Report: {report_path}")
    
    # Summary to stdout
    print("\n" + "=" * 60)
    print("OVERNIGHT REPORT SUMMARY")
    print("=" * 60)
    print(f"Best checkpoint: {best_ckpt}")
    if "step" in best_meta:
        print(f"  Step: {best_meta['step']}, Loss: {best_meta.get('loss', '?')}")
    
    if prior_eval:
        print(f"Prior overall score: {prior_eval.get('overall_score', '?')}/100")
    
    print(f"\nFull report: {report_path}")


if __name__ == "__main__":
    generate_quick_report()
