#!/bin/bash
# Generate training progress report using codex CLI.
# Reads training history + eval results, asks codex to analyze and suggest improvements.
# Output goes to logs/report_YYYY-MM-DD.md

CORE_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$CORE_ROOT"

DATE=$(date +%Y-%m-%d)
TIME=$(date +%H:%M)
REPORT_FILE="logs/report_${DATE}.md"
HISTORY_FILE="logs/training_history.jsonl"
EVAL_FILE="logs/eval_results.json"

mkdir -p logs

# gather training stats
if [ -f "$HISTORY_FILE" ]; then
    TOTAL_EPOCHS=$(wc -l < "$HISTORY_FILE" | tr -d ' ')
    LAST_ENTRY=$(tail -1 "$HISTORY_FILE")
    LAST_LOSS=$(echo "$LAST_ENTRY" | python3 -c "import sys,json; print(json.load(sys.stdin)['loss'])" 2>/dev/null || echo "unknown")
    LAST_EPOCH=$(echo "$LAST_ENTRY" | python3 -c "import sys,json; print(json.load(sys.stdin)['epoch'])" 2>/dev/null || echo "unknown")

    # loss trend (last 10 entries)
    LOSS_TREND=$(tail -10 "$HISTORY_FILE" | python3 -c "
import sys, json
entries = [json.loads(l) for l in sys.stdin]
for e in entries:
    print(f\"  epoch {e['epoch']:4d}: loss {e['loss']:.6f}\")
" 2>/dev/null || echo "  (no data)")
else
    TOTAL_EPOCHS=0
    LAST_LOSS="N/A"
    LAST_EPOCH=0
    LOSS_TREND="  (no training data yet)"
fi

# gather eval stats
if [ -f "$EVAL_FILE" ]; then
    EVAL_SUMMARY=$(python3 -c "
import json
with open('$EVAL_FILE') as f:
    d = json.load(f)
print(f\"Grade: {d['grade']} ({d['overall_score']}/100)\")
print(f\"Epoch: {d['epoch']}, Loss: {d['loss']}\")
for cat, avg in d['category_averages'].items():
    print(f\"  {cat}: {avg}/100\")
print()
print('Sample outputs:')
for r in d['results'][:4]:
    print(f\"  [{r['id']}] score={r['total_score']}\")
    print(f\"    {r['answer'][:100]}\")
" 2>/dev/null || echo "  (eval not run yet)")
else
    EVAL_SUMMARY="  (no eval results yet -- run: python3 cron/evaluate.py)"
fi

# build context for codex
CONTEXT="# Core LLM Training Report - $DATE $TIME

## Model
- Architecture: 4-layer transformer, 128 embed, 4 heads, 512 FF dim
- Params: ~630K
- Tokenizer: char-level
- Data: comprehensive.txt (73K chars, math + jot + identity Q&A)

## Training Progress
- Total epochs trained: $TOTAL_EPOCHS
- Last epoch: $LAST_EPOCH
- Last loss: $LAST_LOSS
- Target: 800 epochs

## Loss Trend (last 10)
$LOSS_TREND

## Evaluation
$EVAL_SUMMARY

## Architecture Notes
- Fixed causal masking bug (was missing, causing good loss but gibberish output)
- Using linear warmup (20 epochs) + cosine decay
- AdamW with weight decay 0.01, grad clipping 1.0
"

# use codex to analyze (no API key needed with --cli codex)
echo "$CONTEXT" > "/tmp/core_report_context.txt"

# try codex first, fall back to writing report directly
if command -v codex &>/dev/null; then
    ANALYSIS=$(CLAUDECODE="" codex --approval-mode full-auto -q "You are analyzing training progress for a small transformer LLM project called 'core'. Based on the following training data, provide:
1. Assessment of current progress (2-3 sentences)
2. Whether the loss curve looks healthy
3. Top 3 specific suggestions to improve model quality
4. Estimated epochs needed before outputs become coherent

Be concise and technical. No fluff.

$CONTEXT" 2>/dev/null || echo "(codex analysis unavailable)")
else
    ANALYSIS="(codex CLI not found -- install with: npm i -g @openai/codex)"
fi

# write report
cat > "$REPORT_FILE" << REPORT_EOF
# Core Training Report - $DATE

Generated: $TIME

## Summary
- Epochs: $LAST_EPOCH / 800
- Loss: $LAST_LOSS
- Sessions logged: $TOTAL_EPOCHS entries

## Loss Trend
$LOSS_TREND

## Evaluation
$EVAL_SUMMARY

## Codex Analysis
$ANALYSIS

---
*Auto-generated by core/cron/report.sh*
REPORT_EOF

echo "Report saved to $REPORT_FILE"
echo ""
cat "$REPORT_FILE"
